### ISSUE TITLE
Travis builds

### ISSUE THREAD

**Issue by dpo** [PythonOptimizers/MUMPS.py#3]
This needs to be validated on TravisCI, both OSX and Linux. Note that it's possible to request specific Linux distributions from TravisCI.

**Comment by syarra** [comment]
I'm not the owner of the repo. Could you enable TravisCI or give me the ownership?

**Comment by dpo** [comment]
Should be ok now.

**Comment by syarra** [comment]
It is working now. Thanks!

**Comment by dpo** [comment]
Ok. Any chance you could try with Linux to see if Andrew's issue is reproducible? You'll need to `apt-get install libblas-dev liblapack-dev libmumps-dev cmake gfortran libopenmpi-dev openmpi-bin`, I think.

**Comment by dpo** [comment]
cc @lambe

**Comment by dpo** [comment]
Can this be closed?
